const months = document.querySelector ("#months")
const weeks = document.querySelector ("#weeks")
const days = document.querySelector ("#days")
const hours = document.querySelector ("#hours")
const minutes = document.querySelector ("#minutes")
const seconds = document.querySelector ("#seconds")
